<?php

namespace themes\pages;
use core\System;

class Main extends \core\Page
{
    public function __construct(){
        System::load_settings();
    }
    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
    }
}