<?php
/**
 * Created by PhpStorm.
 * User: ssaan
 * Date: 25.07.2018
 * Time: 10:20
 */

namespace castom\controllers;


use controllers\Controller;

class FormController extends Controller
{
    function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
        print_r($_REQUEST);
    }
}