<?php

namespace controllers;
use castome\themes\tools\LoginForm;
use core\System;
use core\tools\Button;
use core\tools\EditText;
use core\tools\Form;
use ReflectionObject;
use ReflectionProperty;
use themes\MaterialKatty\tools\MKButton;
use themes\MaterialKatty\tools\MKEditText;
use themes\pages\Main;

class MainController extends Controller
{
    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
        $mainPage = new Main();
        $mainPage->title = "MainPage";
        /*$et1 = new EditText();
        $et1->attributes = ['class' => 'strEdit'];
        $et1->attributes['name'] = 'nick';
        $et2 = new MKEditText();
        $et2->placeholder = 'text';
        $b1 =  new Button("Click");
        $b2 =  new MKButton("Click 3");
        $regForm = new Form();
        $regForm->getElements()->add($et1);
        $regForm->getElements()->add($et2);
        $regForm->getElements()->add($b1);
        $regForm->getElements()->add($b2);*/

        $regForm = new LoginForm();
        $mainPage->content[] = $regForm;
        $mainPage->render();
        //System::rrmdir($_SERVER['DOCUMENT_ROOT'].'/cache');
    }
}