<?php

namespace controllers;
use core\tools\Button;
use core\tools\EditText;
use core\tools\Form;
use themes\NiceKatty\tools\MKButton;
use themes\pages\Main;

class MainController extends Controller
{
    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub
        $mainPage = new Main();
        $mainPage->title = "MainPage";
        $et1 = new EditText();
        $et1->attributes = ['class' => 'strEdit'];
        $et1->attributes['name'] = 'nick';
        $et2 = new EditText();
        $b1 =  new Button("Click");
        $b2 =  new MKButton("Click");
        $regForm = new Form();
        $regForm->elements[] = $et1;
        $regForm->elements[] = $et2;
        $regForm->elements[] = $b1;
        $regForm->elements[] = $b2;
        $mainPage->content[] = $regForm;
        $mainPage->render();
    }
}